require:
  - rubocop-rails

Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  SuggestExtensions: false

Bundler/GemFilename:
  Enabled: false

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_special
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/LineLength:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Lint/SuppressedException:
  AllowComments: true

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 13
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 14

Rails/ApplicationRecord:
  Enabled: false
Rails/ContentTag:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FetchEnvVar:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: either
Style/MutableConstant:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/QuotedSymbols:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
